<!doctype html>
<html lang="en">
<head>
    <title><?= $pageTitle ?> | NintenDB</title>
    <style>
    </style>
    <link href="/+/styles.css" rel="stylesheet" type="text/css" />
</head>
<body>

<div id="index">
    <div id="title">
        <h1>NintenDB</h1>
    </div>

    <div id="nav">
        <ul>
            <li><a href="/-/php/show_games.php">Games</a></li>
            <li><a href="/-/php/search_games.php">Search</a></li>
            <li><a href="#">Sell</a></li>
            <li><a href="#">Signup</a></li>
            <li><a href="#">Login</a></li>
        </ul>
    </div>



    <div id="main">